export const settings = {
    WIDTH: 1050,
    HEIGHT: 800,

    WALL_MARGIN: 50,
    WALL_TURN_FORCE: 0.1,

    BOID_COUNT: 1000,

    BOID_RADIUS: 5,

    MAX_SPEED: 3,
    TURN_SPEED: 0.15,

    VISION_RADIUS: 80,

    SEPARATION_DISTANCE: 25,

    ALIGNMENT_WEIGHT: 0.09,
    COHESION_WEIGHT: 0.03,
    SEPARATION_WEIGHT: 0.1,
};